spring:
  cloud:
    gateway:
      routes:
      - id: movies
        uri: http://localhost:8081/movies
        predicates:
        - Path=/movies/
      - id: books
        uri: http://localhost:8082/books
        predicates:
        - Path=/books/      
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
