hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  cloud:
    gateway:
      routes:
      - id: book-store
        uri: http://book-store
        predicates:
        - Path=/api/books/**

      - id: movie-store
        uri: http://movie-store
        predicates:
        - Path=/api/movies/**
